name: Get Android SHA

on:
  workflow_dispatch:

jobs:
  sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Generate signing report
        run: ./gradlew signingReport
